"""Paleta e tokens semânticos — GitHub Dark Theme."""

import flet as ft

# Base
GH_BG = "#0D1117"
GH_SURFACE = "#161B22"
GH_SURFACE_LIGHT = "#21262D"
GH_SURFACE_HOVER = "#2D333B"
GH_BORDER = "#30363D"
GH_PRIMARY = "#58A6FF"
GH_PRIMARY_HOVER = "#79B8FF"
GH_TEXT_PRIMARY = "#F0F6FC"
GH_TEXT_SECONDARY = "#8B949E"
GH_TEXT_MUTED = "#6E7681"
GH_TEXT_DISABLED = "#484F58"
GH_ERROR = "#F85149"
GH_SUCCESS = "#3FB950"

# Status Kanban
COLOR_PROPOSTA = "#D29922"
COLOR_ORCAMENTO = "#A371F7"
COLOR_PRODUCAO = "#58A6FF"
COLOR_PRONTO = "#3FB950"
COLOR_FATURADO = "#238636"

# Aliases
PRIMARY = GH_PRIMARY
PRIMARY_HOVER = GH_PRIMARY_HOVER
BG_PRIMARY = GH_BG
BG_SURFACE = GH_SURFACE
BG_SURFACE_LIGHT = GH_SURFACE_LIGHT
BG_HOVER = GH_SURFACE_HOVER
BORDER_COLOR = GH_BORDER
BORDER_FOCUS = GH_PRIMARY
TEXT_PRIMARY = GH_TEXT_PRIMARY
TEXT_SECONDARY = GH_TEXT_SECONDARY
TEXT_MUTED = GH_TEXT_MUTED
TEXT_DISABLED = GH_TEXT_DISABLED
ERROR = GH_ERROR
SUCCESS = GH_SUCCESS
